import { Router, type IRouter } from "express";
import { aiRateLimit, defaultRateLimit } from "../middlewares/rate-limit.js";
import healthRouter from "./health.js";
import versionRouter from "./version.js";
import authRouter from "./auth.js";
import briefingRouter from "./briefing.js";
import conversationsRouter from "./conversations.js";
import tasksRouter from "./tasks.js";
import projectsRouter from "./projects.js";
import contactsRouter from "./contacts.js";
import memoriesRouter from "./memories.js";
import decisionsRouter from "./decisions.js";
import assetsRouter from "./assets.js";
import dashboardRouter from "./dashboard.js";
import notificationsRouter from "./notifications.js";
import studioRouter from "./studio.js";
import studioGenerateRouter from "./studio-generate.js";
import studioVideoRouter from "./studio-video.js";
import studioMusicRouter from "./studio-music.js";
import studioProvidersRouter from "./studio-providers.js";
import studioOrchestrateRouter from "./studio-orchestrate.js";
import studioEditorRouter from "./studio-editor.js";
import gpuWorkersRouter from "./gpu-workers.js";
import productionDiagnosticsRouter from "./production-diagnostics.js";
import systemRouter from "./system.js";
import systemReadinessRouter from "./system-readiness.js";
import recoveryRouter from "./recovery.js";
import lifeOsRouter from "./life-os.js";
import platformLifeOsFinalRouter from "./platform-life-os-final.js";
import observabilityRouter from "./observability.js";
import agentsRouter from "./agents.js";
import integrationsRouter from "./integrations.js";
import selfDevRouter from "./self-dev.js";
import workflowsRouter from "./workflows.js";
import exportRouter from "./export.js";
import missionsRouter from "./missions.js";
import kernelRouter from "./kernel.js";
import devRuntimeRouter from "./dev-runtime.js";
import devAgentCoreRouter from "./dev-agent-core.js";
import devAgentValidationRouter from "./dev-agent-validation.js";
import ciOperatorRouter from "./dev-agent-ci.js";
import devAgentSchedulerRouter from "./dev-agent-scheduler.js";
import devAgentProRouter from "./dev-agent-pro.js";
import capabilityRegistryRouter from "./capability-registry.js";
import capabilityActionsMediaDevopsRouter from "./capability-actions-media-devops.js";
import capabilityActionsMemoryRouter from "./capability-actions-memory.js";
import capabilityActionsRouter from "./capability-actions.js";
import chatCapabilitiesRouter from "./chat-capabilities.js";
import n8nWebhookRouter from "./n8n-webhook.js";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(versionRouter);
router.use(briefingRouter);
router.use("/conversations", aiRateLimit);
router.use(conversationsRouter);
router.use("/agents", aiRateLimit);
router.use(agentsRouter);
router.use(selfDevRouter);
router.use(tasksRouter);
router.use(projectsRouter);
router.use(contactsRouter);
router.use(memoriesRouter);
router.use(decisionsRouter);
router.use(assetsRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use("/studio", aiRateLimit);
router.use(studioRouter);
router.use(studioGenerateRouter);
router.use(studioVideoRouter);
router.use(studioMusicRouter);
router.use(studioProvidersRouter);
router.use(studioOrchestrateRouter);
router.use(studioEditorRouter);
router.use(gpuWorkersRouter);
router.use(productionDiagnosticsRouter);
router.use(systemRouter);
router.use(systemReadinessRouter);
router.use(recoveryRouter);
router.use(lifeOsRouter);
router.use(platformLifeOsFinalRouter);
router.use(observabilityRouter);
router.use(integrationsRouter);
router.use(workflowsRouter);
router.use(exportRouter);
router.use(missionsRouter);
router.use(kernelRouter);
router.use(devRuntimeRouter);
router.use(devAgentCoreRouter);
router.use(devAgentValidationRouter);
router.use(ciOperatorRouter);
router.use(devAgentSchedulerRouter);
router.use(devAgentProRouter);
router.use(capabilityActionsMediaDevopsRouter);
router.use(capabilityActionsMemoryRouter);
router.use(capabilityActionsRouter);
router.use(capabilityRegistryRouter);
router.use(chatCapabilitiesRouter);
router.use(n8nWebhookRouter);
router.use(defaultRateLimit);

export default router;
