import { Router, type IRouter } from "express";
import { aiRateLimit, defaultRateLimit } from "../middlewares/rate-limit.js";
import healthRouter from "./health.js";
import versionRouter from "./version.js";
import authRouter from "./auth.js";
import briefingRouter from "./briefing.js";
import conversationsRouter from "./conversations.js";
import tasksRouter from "./tasks.js";
import projectsRouter from "./projects.js";
import contactsRouter from "./contacts.js";
import memoriesRouter from "./memories.js";
import decisionsRouter from "./decisions.js";
import assetsRouter from "./assets.js";
import dashboardRouter from "./dashboard.js";
import notificationsRouter from "./notifications.js";
import studioRouter from "./studio.js";
import studioGenerateRouter from "./studio-generate.js";
import studioVideoRouter from "./studio-video.js";
import studioMusicRouter from "./studio-music.js";
import studioOrchestrateRouter from "./studio-orchestrate.js";
import systemRouter from "./system.js";
import systemReadinessRouter from "./system-readiness.js";
import observabilityRouter from "./observability.js";
import agentsRouter from "./agents.js";
import integrationsRouter from "./integrations.js";
import selfDevRouter from "./self-dev.js";
import workflowsRouter from "./workflows.js";
import exportRouter from "./export.js";
import missionsRouter from "./missions.js";
import kernelRouter from "./kernel.js";
import devRuntimeRouter from "./dev-runtime.js";
import capabilityRegistryRouter from "./capability-registry.js";
import capabilityActionsMemoryRouter from "./capability-actions-memory.js";
import capabilityActionsRouter from "./capability-actions.js";
import chatCapabilitiesRouter from "./chat-capabilities.js";

const router: IRouter = Router();

// Auth routes - public (no auth required)
router.use(authRouter);

// Health routes - public
router.use(healthRouter);
router.use(versionRouter);

router.use(briefingRouter);
router.use("/conversations", aiRateLimit);
router.use(conversationsRouter);
router.use("/agents", aiRateLimit);
router.use(agentsRouter);
router.use(selfDevRouter);
router.use(tasksRouter);
router.use(projectsRouter);
router.use(contactsRouter);
router.use(memoriesRouter);
router.use(decisionsRouter);
router.use(assetsRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use("/studio", aiRateLimit);
router.use(studioRouter);
router.use(studioGenerateRouter);
router.use(studioVideoRouter);
router.use(studioMusicRouter);
router.use(studioOrchestrateRouter);
router.use(systemRouter);
router.use(systemReadinessRouter);
router.use(observabilityRouter);
router.use(integrationsRouter);
router.use(workflowsRouter);
router.use(exportRouter);
router.use(missionsRouter);
router.use(kernelRouter);
router.use(devRuntimeRouter);
router.use(capabilityActionsMemoryRouter);
router.use(capabilityActionsRouter);
router.use(capabilityRegistryRouter);
router.use(chatCapabilitiesRouter);
router.use(defaultRateLimit);

export default router;
