import { execFile } from "node:child_process";
import { mkdir, writeFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { Router } from "express";
import { generateMusic } from "../lib/audio.js";
import { generateSlideshowVideo, VIDEO_DIR } from "../lib/video.js";

const router = Router();
const execFileAsync = promisify(execFile);

type CheckStatus = "pass" | "warn" | "fail";
type Check = { status: CheckStatus; detail: string; data?: Record<string, unknown> };

function has(name: string) {
  const value = process.env[name];
  return typeof value === "string" && value.trim().length > 0;
}

function any(names: string[]) {
  return names.some(has);
}

function first(names: string[]) {
  for (const name of names) {
    const value = process.env[name];
    if (typeof value === "string" && value.trim()) return { source: name, value: value.trim() };
  }
  return null;
}

async function ffmpegCheck(): Promise<Check> {
  try {
    const { stdout } = await execFileAsync("ffmpeg", ["-version"], { timeout: 4000, maxBuffer: 80_000 });
    return { status: "pass", detail: stdout.split("\n")[0] || "ffmpeg available" };
  } catch (error) {
    return { status: "fail", detail: error instanceof Error ? error.message : String(error) };
  }
}

async function tempCheck(): Promise<Check> {
  const dir = path.join(os.tmpdir(), "tams-diagnostics");
  const file = path.join(dir, `probe-${Date.now()}.txt`);
  try {
    await mkdir(dir, { recursive: true });
    await writeFile(file, "ok");
    await rm(file, { force: true });
    return { status: "pass", detail: "temp writable", data: { tmpdir: os.tmpdir() } };
  } catch (error) {
    return { status: "fail", detail: error instanceof Error ? error.message : String(error), data: { tmpdir: os.tmpdir() } };
  }
}

function dbCheck(): Check {
  return has("DATABASE_URL")
    ? { status: "pass", detail: "database env configured; query not executed by public diagnostics" }
    : { status: "warn", detail: "database env missing" };
}

function routesCheck(): Check {
  return {
    status: "pass",
    detail: "diagnostic route is loaded",
    data: {
      studio: ["/api/studio/generate-video", "/api/studio/generate-music", "/api/studio/generate-image"],
      gpu: ["/api/gpu/status", "/api/gpu/jobs"],
      system: ["/api/healthz", "/api/version"],
      n8n: ["/api/n8n/status"],
    },
  };
}

function verdict(checks: Record<string, Check>) {
  const values = Object.values(checks).map(c => c.status);
  if (values.includes("fail")) return "fail";
  if (values.includes("warn")) return "warn";
  return "pass";
}

async function studioVideoSelfTest(): Promise<Check> {
  try {
    const result = await generateSlideshowVideo({
      images: [],
      text: "TAMS Studio self-test MP4",
      secondsPerImage: 1,
    });
    const url = result.url;
    const file = typeof url === "string" ? url.split("/").pop() : undefined;
    const exists = file ? path.join(VIDEO_DIR, file) : null;
    if (!url || !exists) return { status: "fail", detail: "video generation returned no file url" };
    return {
      status: "pass",
      detail: "real MP4 generated by Studio backend",
      data: { url, engine: result.engine, degraded: result.degraded, duration: result.durationSec, fileExistsPath: exists },
    };
  } catch (error) {
    return { status: "fail", detail: error instanceof Error ? error.message : String(error) };
  }
}

async function studioAudioSelfTest(): Promise<Check> {
  try {
    const result = await generateMusic("TAMS Studio self-test audio");
    if (!result.ok || !result.url) return { status: "fail", detail: result.error || "audio generation returned no url" };
    return {
      status: "pass",
      detail: "real audio generated by Studio backend",
      data: { url: result.url, engine: result.engine, degraded: result.degraded, bytes: result.bytes },
    };
  } catch (error) {
    return { status: "fail", detail: error instanceof Error ? error.message : String(error) };
  }
}

function studioImageSelfTest(): Check {
  const prompt = encodeURIComponent("TAMS Studio self-test image");
  const url = `https://image.pollinations.ai/prompt/${prompt}?width=512&height=512&nologo=true&model=flux&seed=4242`;
  return { status: "pass", detail: "image endpoint URL generated", data: { url, engine: "pollinations" } };
}

function workersCheck(): Check {
  const gpu = {
    video: has("STUDIO_GPU_VIDEO_URL") || has("STUDIO_GPU_GENERAL_URL"),
    audio: has("STUDIO_GPU_AUDIO_URL") || has("STUDIO_GPU_GENERAL_URL"),
    voice: has("STUDIO_GPU_VOICE_URL") || has("STUDIO_GPU_GENERAL_URL"),
    vision: has("STUDIO_GPU_VISION_URL") || has("STUDIO_GPU_GENERAL_URL"),
    image: has("STUDIO_GPU_IMAGE_URL") || has("STUDIO_GPU_GENERAL_URL"),
    n8n: has("N8N_WEBHOOK_URL"),
    comfyui: has("COMFYUI_BASE_URL"),
  };
  const connected = Object.entries(gpu).filter(([, v]) => v).length;
  const total = Object.keys(gpu).length;
  return {
    status: "pass",
    detail: `${connected}/${total} workers configured`,
    data: { ...gpu, connected, total },
  };
}

router.get("/_diagnostics/studio-selftest", async (_req, res) => {
  const checks: Record<string, Check> = {
    tempWrite: await tempCheck(),
    ffmpeg: await ffmpegCheck(),
    video: await studioVideoSelfTest(),
    audio: await studioAudioSelfTest(),
    image: studioImageSelfTest(),
    workers: workersCheck(),
  };
  const v = verdict(checks);
  res.status(v === "fail" ? 503 : 200).json({
    ok: v !== "fail",
    verdict: v,
    checkedAt: new Date().toISOString(),
    checks,
    playable: {
      videoUrl: checks.video.data?.url ?? null,
      audioUrl: checks.audio.data?.url ?? null,
      imageUrl: checks.image.data?.url ?? null,
    },
    workers: checks.workers.data,
    safety: { secretsExposed: false },
  });
});

router.get("/_diagnostics/production", async (_req, res) => {
  const checks: Record<string, Check> = {
    routes: routesCheck(),
    tempWrite: await tempCheck(),
    ffmpeg: await ffmpegCheck(),
    database: dbCheck(),
    workers: workersCheck(),
  };

  const commit = first(["RAILWAY_GIT_COMMIT_SHA", "GIT_COMMIT_SHA", "SOURCE_VERSION", "COMMIT_SHA"]);
  const env = {
    railwayDetected: any(["RAILWAY_ENVIRONMENT", "RAILWAY_PROJECT_ID", "RAILWAY_SERVICE_ID", "RAILWAY_DEPLOYMENT_ID"]),
    databaseConfigured: has("DATABASE_URL"),
    audioProviderConfigured: any(["HF_TOKEN", "HUGGINGFACE_API_KEY"]),
    workflowProviderConfigured: has("N8N_WEBHOOK_URL"),
    gpuVideoConfigured: any(["STUDIO_GPU_VIDEO_URL", "STUDIO_GPU_GENERAL_URL"]),
    gpuAudioConfigured: any(["STUDIO_GPU_AUDIO_URL", "STUDIO_GPU_GENERAL_URL"]),
    gpuVoiceConfigured: any(["STUDIO_GPU_VOICE_URL", "STUDIO_GPU_GENERAL_URL"]),
    gpuVisionConfigured: any(["STUDIO_GPU_VISION_URL", "STUDIO_GPU_GENERAL_URL"]),
    gpuImageConfigured: any(["STUDIO_GPU_IMAGE_URL", "STUDIO_GPU_GENERAL_URL"]),
    comfyuiConfigured: has("COMFYUI_BASE_URL"),
  };

  const v = verdict(checks);
  const studioFallback = checks.ffmpeg.status === "pass" && checks.tempWrite.status === "pass";

  res.status(v === "fail" ? 503 : 200).json({
    ok: v !== "fail",
    verdict: v,
    checkedAt: new Date().toISOString(),
    deployment: {
      sha: commit?.value ?? "unknown",
      shaSource: commit?.source ?? null,
      railway: env.railwayDetected,
    },
    runtime: {
      node: process.version,
      platform: process.platform,
      arch: process.arch,
      uptimeSec: Math.round(process.uptime()),
      tmpdir: os.tmpdir(),
      nodeEnv: process.env.NODE_ENV ?? "unknown",
    },
    env,
    checks,
    capabilities: {
      studioVideoFallbackUsable: studioFallback,
      studioAudioFallbackUsable: checks.tempWrite.status === "pass",
      gpuWorkersUsable: env.gpuVideoConfigured || env.gpuAudioConfigured || env.gpuVoiceConfigured || env.gpuVisionConfigured,
      premiumVideoUsable: env.gpuVideoConfigured,
      databaseBackedFeaturesLikelyUsable: env.databaseConfigured,
      n8nAutomationUsable: env.workflowProviderConfigured,
      comfyuiUsable: env.comfyuiConfigured,
    },
    safety: {
      secretsExposed: false,
      note: "Only booleans and runtime facts are returned. Secret values are never returned.",
    },
    nextChecks: [
      "Open /api/_diagnostics/studio-selftest and verify playable URLs.",
      "Open /studio and verify one video returns a playable media URL.",
    ],
  });
});

export default router;
